name: Create release

on:
  push:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest>
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1.6.1
        with:
          python_ver: '3.0'
          pyinstaller_ver: '==6.11.1'
          spec: 'src/application.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'FastAudioMerge'
          options: --onefile, --name "FastAudioMerge", --windowed, --noconsole 
