name: Create Release

on:
  push:
    branches:
      - main

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements_windows.txt', 'requirements_linux.txt', 'requirements_macos.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ "${{ runner.os }}" = "Linux" ]; then
          pip install -r requirements_linux.txt
        elif [ "${{ runner.os }}" = "macOS" ]; then
          pip install -r requirements_macos.txt
        else
          pip install -r requirements_windows.txt
        fi

    - name: Build executable with PyInstaller
      shell: bash
      run: |
        mkdir build_output
        cp -r src/* build_output/
        cd build_output
        pip install pyinstaller==6.11.1
        pyinstaller --onefile --windowed --name "FastAudioMerge" --target-arch universal2 application.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FastAudioMerge-${{ matrix.os }}
        path: build_output/dist/FastAudioMerge*
