name: Create release

on:
  push:
    branches:
      - main

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        mkdir build_output
        cp -r src/* build_output/

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          ADD_DATA="thread_merge.py;."
        else
          ADD_DATA="thread_merge.py:."
        fi

        cd build_output
        pip install pyinstaller==6.11.1
        pyinstaller --onefile --name "FastAudioMerge" --windowed --noconsole \
          --add-data "$ADD_DATA" application.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FastAudioMerge-${{ matrix.os }}
        path: build_output/dist/FastAudioMerge*
